project:
  type: website

website:
  page-navigation: true
  site-url: "https://mathisgiraud.com/"
  title: "Mon premier blog - Mathis GIRAUD"
  page-footer:
    left: "Blog made with Quarton(https://quarto.org/), by Mathis GIRAUD"
    right:
      - icon: github
        href: https://github.com/mathis-giraud/
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mathis-giraud
      - icon: share
        href: https://e1.pcloud.link/publink/show?code=XZDCnbZwsrNMLgTOqQXqrn2OAbii7YFfJ3X

format:
  html:
    smooth-scroll: true
    theme: journal
    css: styles.css
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.mathisgiraud\.com\/**'
    citations-hover: true
    footnotes-hover: true
    include-in-header: meta.html
    toc: true
    code-link: true

editor: visual
