project:
  type: website

website:
  title: "Mon premier blog - Mathis GIRAUD"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mathis-giraud
      - icon: share
        href: https://e1.pcloud.link/publink/show?code=XZDCnbZwsrNMLgTOqQXqrn2OAbii7YFfJ3X
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

